In [23]:
import pandas as pd

In [73]:
# Load Dataset
# data = pd.read_csv('/Users/ab/Documents/GreenGrass/June_2024.csv')
# data = pd.read_csv('/Users/ab/Documents/GreenGrass/September_2024.csv')
# data = pd.read_csv('/Users/ab/Documents/GreenGrass/January_2024.csv')
# data = pd.read_csv('/Users/ab/Documents/GreenGrass/February_2024.csv')
# data = pd.read_csv('/Users/ab/Documents/GreenGrass/March_2024.csv')
#data = pd.read_csv('/Users/ab/Documents/GreenGrass/April_2024.csv')
data = pd.read_csv('/Users/ab/Documents/GreenGrass/May_2024.csv')

In [75]:
# Prepare Dataframe
df = pd.DataFrame(data)

In [77]:
# Rename Readable Collumn Name
df = df.rename(columns={'S No.': 'index', 'Value Date': 'value_date', 'Transaction Date': 'transaction_date', 'Cheque Number': 'check_no', 'Transaction Remarks': 'remark', 'Withdrawal Amount (INR )': 'debit', 'Deposit Amount (INR )': 'credit'})

In [79]:
total_debits = df['debit'].sum()
print(f"Total Debit Transation : {total_debits.round()}")

Total Debit Transation : 381509.0

In [81]:
total_transaction = df['debit'].count()
total_transaction_sum = df['debit'].sum()
tracked_transactions_count = 0
tracked_transactions = 0

# Report DataFrame
report_df = pd.DataFrame(columns= ['# Type', '# Count', '# Amount'])
report_df.loc[len(report_df)] = ['All Debits', total_transaction, total_transaction_sum]

# Summary DataFrame
summary_df = pd.DataFrame(columns= ['Category', '# Count', '% Distribution', '# Amount'])

# Swiggy
swiggy_trans_count = df['remark'].str.contains('swiggy').sum()
# swiggy_trans_amount_sum = swiggy_trans['debit'].sum()
swiggy_trans_distribution = (swiggy_trans_count / total_transaction) * 100
swiggy_trans = df[df['remark'].str.contains('swiggy', na=False)]
swiggy_trans_sum = swiggy_trans['debit'].sum()
tracked_transactions += swiggy_trans_sum
tracked_transactions_count += swiggy_trans_count
summary_df.loc[len(summary_df)] = ['Swiggy', swiggy_trans_count, swiggy_trans_distribution.round(), swiggy_trans_sum]

# Amazon
amazon_trans_count = df['remark'].str.contains('amazon').sum()
amazon_trans_distribution = (amazon_trans_count / total_transaction) * 100
tracked_transactions_count += amazon_trans_count
amazon_trans = df[df['remark'].str.contains('Amazon', na=False)]
amazon_trans_sum = amazon_trans['debit'].sum()
tracked_transactions += amazon_trans_sum
summary_df.loc[len(summary_df)] = ['Amazon', amazon_trans_count, amazon_trans_distribution.round(), amazon_trans_sum]

# Airtel
airtel_trans_count = df['remark'].str.contains('airtel').sum()
airtel_trans_distribution = (airtel_trans_count / total_transaction) * 100
tracked_transactions_count += airtel_trans_count
airtel_trans = df[df['remark'].str.contains('airtel', na=False)]
airtel_trans_sum = airtel_trans['debit'].sum()
tracked_transactions += airtel_trans_sum
summary_df.loc[len(summary_df)] = ['Airtel Bill', airtel_trans_count, airtel_trans_distribution.round(), airtel_trans_sum]

# Spotify
spotify_trans_count = df['remark'].str.contains('spotify').sum()
spotify_trans_distribution = (spotify_trans_count / total_transaction) * 100
tracked_transactions_count += spotify_trans_count
spotify_trans = df[df['remark'].str.contains('spotify', na=False)]
spotify_trans_sum = spotify_trans['debit'].sum()
tracked_transactions += spotify_trans_sum
summary_df.loc[len(summary_df)] = ['Spotify Bill', spotify_trans_count, spotify_trans_distribution.round(), spotify_trans_sum]

# House Rent
house_rent_trans_count = df['remark'].str.contains('LAKSHM').sum()
house_rent_trans_distribution = (spotify_trans_count / total_transaction) * 100
tracked_transactions_count += house_rent_trans_count
house_rent_trans = df[df['remark'].str.contains('LAKSHM', na=False)]
house_rent_trans_sum = house_rent_trans['debit'].sum()
tracked_transactions += house_rent_trans_sum
summary_df.loc[len(summary_df)] = ['House Rent', house_rent_trans_count, house_rent_trans_distribution.round(), house_rent_trans_sum]

# BookMyShow
bookmyshow_trans_count = df['remark'].str.contains('bookmyshow').sum()
bookmyshow_trans_distribution = (bookmyshow_trans_count / total_transaction) * 100
tracked_transactions_count += bookmyshow_trans_count
bookmyshow_trans = df[df['remark'].str.contains('bookmyshow', na=False)]
bookmyshow_trans_sum = bookmyshow_trans['debit'].sum()
tracked_transactions += bookmyshow_trans_sum
summary_df.loc[len(summary_df)] = ['BookMyShow', bookmyshow_trans_count, bookmyshow_trans_distribution.round(), bookmyshow_trans_sum]

# Groww Monthly Mutual Fund SIP
sip_pattern = '|'.join(['SIP', 'Grow'])
groww_trans_count = df['remark'].str.contains(sip_pattern).sum()
groww_trans_distribution = (groww_trans_count / total_transaction) * 100
tracked_transactions_count += groww_trans_count
groww_trans = df[df['remark'].str.contains(sip_pattern, na=False)]
groww_trans_sum = groww_trans['debit'].sum()
tracked_transactions += groww_trans_sum
summary_df.loc[len(summary_df)] = ['Groww SIP', groww_trans_count, groww_trans_distribution.round(), groww_trans_sum]

# Zerodha Stocks
zerodha_trans_count = df['remark'].str.contains('zerodha').sum()
zerodha_trans_distribution = (zerodha_trans_count / total_transaction) * 100
tracked_transactions_count += zerodha_trans_count
zerodha_trans = df[df['remark'].str.contains('zerodha', na=False)]
zerodha_trans_sum = zerodha_trans['debit'].sum()
tracked_transactions += zerodha_trans_sum
summary_df.loc[len(summary_df)] = ['Stocks+Equity', zerodha_trans_count, zerodha_trans_distribution.round(), zerodha_trans_sum]

# Netflix
netflix_trans_count = df['remark'].str.contains('netflix').sum()
netflix_trans_distribution = (netflix_trans_count / total_transaction) * 100
tracked_transactions_count += netflix_trans_count
netflix_trans = df[df['remark'].str.contains('netflix', na=False)]
netflix_trans_sum = netflix_trans['debit'].sum()
tracked_transactions += netflix_trans_sum
summary_df.loc[len(summary_df)] = ['Netflix', netflix_trans_count, netflix_trans_distribution.round(), netflix_trans_sum]

# Health + Manipal Hospital
health_pattern = '|'.join(['ManipalHospital', 'Hospital'])
health_trans_count = df['remark'].str.contains(health_pattern).sum()
health_trans_distribution = (health_trans_count / total_transaction) * 100
tracked_transactions_count += health_trans_count
health_trans = df[df['remark'].str.contains(health_pattern, na=False)]
health_trans_sum = zerodha_trans['debit'].sum()
tracked_transactions += health_trans_sum
summary_df.loc[len(summary_df)] = ['Hospital Bills', health_trans_count, health_trans_distribution.round(), health_trans_sum]

# Godrej Property
godrej_trans_count = df['remark'].str.contains('GODREJ').sum()
godrej_trans_distribution = (godrej_trans_count / total_transaction) * 100
tracked_transactions_count += godrej_trans_distribution
godrej_trans = df[df['remark'].str.contains('GODREJ', na=False)]
godrej_trans_sum = godrej_trans['debit'].sum()
tracked_transactions += godrej_trans_sum
summary_df.loc[len(summary_df)] = ['Godrej Flat EMI', godrej_trans_count, godrej_trans_distribution.round(), godrej_trans_sum]

# Grocessories 

# Petrol
petrol_trans_count = df['remark'].str.contains('paytm-113645').sum()
petrol_trans_distribution = (petrol_trans_count / total_transaction) * 100
tracked_transactions_count += petrol_trans_distribution
petrol_trans = df[df['remark'].str.contains('paytm-113645', na=False)]
petrol_trans_sum = petrol_trans['debit'].sum()
tracked_transactions += petrol_trans_sum
summary_df.loc[len(summary_df)] = ['Petrol Refill', petrol_trans_count, petrol_trans_distribution.round(), petrol_trans_sum]

# Rentomojo
rentomojo_trans_count = df['remark'].str.contains('razorpay.2@ic').sum()
rentomojo_trans_distribution = (rentomojo_trans_count / total_transaction) * 100
tracked_transactions_count += rentomojo_trans_distribution
rentomojo_trans = df[df['remark'].str.contains('razorpay.2@ic', na=False)]
rentomojo_trans_sum = rentomojo_trans['debit'].sum()
tracked_transactions += rentomojo_trans_sum
summary_df.loc[len(summary_df)] = ['Furniture Rent', rentomojo_trans_count, rentomojo_trans_distribution.round(), rentomojo_trans_sum]

# Electricity Bill

# Internet Bill

# Benu Househelp

# CreditCard (Flight Tickets + Adobe Subs)
creditcard_trans_count = df['remark'].str.contains('CREDIT CA').sum()
creditcard_trans_distribution = (creditcard_trans_count / total_transaction) * 100
tracked_transactions_count += creditcard_trans_distribution
creditcard_trans = df[df['remark'].str.contains('CREDIT CA', na=False)]
creditcard_trans_sum = creditcard_trans['debit'].sum()
tracked_transactions += creditcard_trans_sum
summary_df.loc[len(summary_df)] = ['Credit Card Bill', creditcard_trans_count, creditcard_trans_distribution.round(), creditcard_trans_sum]

# Apple

# Google

print()

# Transactions Summary
unaccounted_transactions_count = total_transaction - tracked_transactions_count
report_df.loc[len(report_df)] = ['Tracked Debits', total_transaction - unaccounted_transactions_count, tracked_transactions]
report_df.loc[len(report_df)] = ['Unaccounted Debits', unaccounted_transactions_count, total_transaction_sum - tracked_transactions]

In [83]:
report_df

               # Type     # Count   # Amount
0          All Debits  150.000000  381509.01
1      Tracked Debits   42.666667   79097.32
2  Unaccounted Debits  107.333333  302411.69

In [85]:
summary_df

            Category  # Count  % Distribution  # Amount
0             Swiggy       20            13.0  10250.00
1             Amazon       13             9.0   1789.00
2        Airtel Bill        0             0.0      0.00
3       Spotify Bill        1             1.0    119.00
4         House Rent        1             1.0  34000.00
5         BookMyShow        1             1.0    539.14
6          Groww SIP        3             2.0  25000.00
7      Stocks+Equity        0             0.0      0.00
8            Netflix        1             1.0    649.00
9     Hospital Bills        0             0.0      0.00
10   Godrej Flat EMI        1             1.0    590.00
11     Petrol Refill        1             1.0    250.00
12    Furniture Rent        1             1.0   4284.50
13  Credit Card Bill        1             1.0   1626.68